name: xpass
description: "Xpass, una aplicación de gestión de contraseñas."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^11.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  encrypt: ^5.0.1
  google_fonts: ^6.2.1
  cryptography: ^2.7.0
  device_info_plus: ^11.1.1

  asn1lib: ^1.5.8
  file_picker: ^8.1.4
  sqflite: ^2.4.1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  xkyber_crypto: ^1.0.3
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png" 


flutter:
  uses-material-design: true
  assets:
    - icon.png



  